Assignment -1

Name : Aman Varma Rudraraju

Reg.No: 20BDS0325

Mail: amanvarma.rudraraju2020@vitstudent.ac.in

In [18]:
import numpy as np
import pandas as pd

In [22]:
# Task - 1 Create a pandas dataframe (DataFrame name as 'df') with numpy random values (4 features and 4 observation)

df=pd.DataFrame([pd.Series(np.random.rand(4)),pd.Series(np.random.rand(4)),pd.Series(np.random.rand(4)),pd.Series(np.random.rand(4))])
df

          0         1         2         3
0  0.838883  0.211234  0.454329  0.064104
1  0.191921  0.407067  0.650043  0.400346
2  0.020983  0.035749  0.370947  0.698120
3  0.132570  0.591013  0.735271  0.195725

In [20]:
# Task - 2 Rename the task - 1 'df' dataframe column names to 'Random value 1', 'Random value 2', 'Random value 3' & 'Random value 4'

df.columns=['Random value 1','Random value 2','Random value 3','Random value 4']
df

   Random value 1  Random value 2  Random value 3  Random value 4
0        0.862885        0.295446        0.003927        0.253115
1        0.880066        0.902107        0.446834        0.861977
2        0.186461        0.725413        0.116470        0.028033
3        0.389998        0.290122        0.153391        0.097377

In [21]:
# Task - 3 Find the descriptive statistics of the 'df' dataframe.

df.describe(include='all')

       Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.579852        0.553272        0.180155        0.310126
std          0.346909        0.309322        0.188809        0.379749
min          0.186461        0.290122        0.003927        0.028033
25%          0.339114        0.294115        0.088334        0.080041
50%          0.626441        0.510430        0.134930        0.175246
75%          0.867180        0.769587        0.226751        0.405331
max          0.880066        0.902107        0.446834        0.861977

In [13]:
# Task - 4 Check for the null values in 'df' and find the data type of the columns.

df.isnull()

   Random value 1  Random value 2  Random value 3  Random value 4
0           False           False           False           False
1           False           False           False           False
2           False           False           False           False
3           False           False           False           False

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Random value 1  4 non-null      float64
 1   Random value 2  4 non-null      float64
 2   Random value 3  4 non-null      float64
 3   Random value 4  4 non-null      float64
dtypes: float64(4)
memory usage: 256.0 bytes

In [17]:
# Task - 5 Display the 'Random value 2' & 'Random value 3' columns with location method and index location method.

df.loc[:,'Random value 2':'Random value 3']

   Random value 2  Random value 3
0        0.270233        0.408368
1        0.257108        0.344175
2        0.112143        0.978919
3        0.391860        0.243195

In [15]:
df.iloc[:,1:3]

   Random value 2  Random value 3
0        0.270233        0.408368
1        0.257108        0.344175
2        0.112143        0.978919
3        0.391860        0.243195